version: '3.1'

services:
   tomcat:
      image: tomcat:9.0.17-jre8-alpine
      container_name: tomcat-city
      restart: always
      ports:
       - 8080:8080
      volumes:
      - webapps:/usr/local/tomcat/webapps

volumes:
   webapps:
